version: "3"
services:
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
      PROJECT: TEST
    ports:
      - "5050:5050"
    volumes:
      - ${PWD}/target/allure-results:/app/allure-results
      - ${PWD}/target/allure-reports:/app/default-reports

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"


  node-docker:
    image: selenium/node-docker:4.8.3-20230404
    volumes:
      - ./assets:/opt/selenium/assets:ro
      - ./assets/config.toml:/opt/bin/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
      - SE_OPTS=--override-max-sessions true --max-sessions 4 --session-timeout 7200 --log /dev/null
      - VNC_PASSWORD=test
    networks:
      testsnw: { }

  selenium-hub:
    image: selenium/hub:4.8.3-20230404
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      testsnw: { }

  study_case:
    depends_on:
      - selenium-hub
      - node-docker
    environment:
      - BROWSER=${BROWSER}
      - RUNNER=${RUNNER}
      - TAG=${TAG}
      - THREAD_COUNT=${THREAD_COUNT}

    networks:
      testsnw: { }
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./target:/home/webStudyCase/target
networks:
  testsnw:
    driver: bridge